version: '3.8'

services:
  broker:
    container_name: celery-broker
    image: rabbitmq:3.8.18-management-alpine
    ports:
      - "8080:15672"
      - "5672:5672"
    networks:
      - network

  backend:
    container_name: celery-backend
    image: redis:6.2.4
    ports:
      - "6379:6379"
    networks:
      - network
    command: redis-server --requirepass password

  imagery_worker:
    build: ./src/workers/imagery
    container_name: celery-imagery
    env_file:
      - 'variables.env'
    volumes:
      - './data/images:/workers/data'
    environment:
      - BUCKET_NAME=fashion-tasks
      - DATA_FOLDER=data
    links:
      - backend:backend
      - broker:broker
    networks:
      - network
    depends_on:
      - client
    command: celery worker -A worker.imagery --loglevel=INFO

  api:
    build: ./src/api
    container_name: fashion-api
    env_file:
      - 'variables.env'
    links:
      - backend:backend
      - broker:broker
      - database:database
      - localstack:localstack
    ports:
      - "5000:5000"
    networks:
      - network

  client:
    build: ./src/client
    container_name: fashion-client
    volumes:
      - ./src/client/notebooks:/home/jovyan/notebooks
    ports:
      - 8888:8888
    env_file:
      - 'variables.env'
    links:
      - backend:backend
      - broker:broker
      - api:api
      - localstack:localstack
    depends_on:
      - localstack
#      - api
    networks:
      - network

  database:
    build: ./src/database
    env_file:
      - 'variables.env'
    volumes:
      - ./tmp/database:/tmp/database
    ports:
      - 5432:5432
    networks:
      - network

  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    ports:
      - 4566:4566
    volumes:
      - './tmp/aws:/tmp/localstack/data'
      - './data/images:/tmp/localstack/dataset'
      - './src/localstack:/docker-entrypoint-initaws.d'
    networks:
      - network

networks:
    network: {}